# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(738, 489)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playersTable = QtWidgets.QTableView(self.centralwidget)
        self.playersTable.setObjectName("playersTable")
        self.horizontalLayout.addWidget(self.playersTable)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setIconSize(QtCore.QSize(10, 10))
        self.refreshButton.setFlat(False)
        self.refreshButton.setObjectName("refreshButton")
        self.verticalLayout.addWidget(self.refreshButton)
        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportButton.setObjectName("exportButton")
        self.verticalLayout.addWidget(self.exportButton)
        self.gotoRow = QtWidgets.QLineEdit(self.centralwidget)
        self.gotoRow.setObjectName("gotoRow")
        self.verticalLayout.addWidget(self.gotoRow)
        self.gotoRowOk = QtWidgets.QPushButton(self.centralwidget)
        self.gotoRowOk.setObjectName("gotoRowOk")
        self.verticalLayout.addWidget(self.gotoRowOk)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.mostExpensivePlayer = QtWidgets.QLabel(self.centralwidget)
        self.mostExpensivePlayer.setObjectName("mostExpensivePlayer")
        self.verticalLayout.addWidget(self.mostExpensivePlayer)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lessExpensivePlayer = QtWidgets.QLabel(self.centralwidget)
        self.lessExpensivePlayer.setObjectName("lessExpensivePlayer")
        self.verticalLayout.addWidget(self.lessExpensivePlayer)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout.addWidget(self.exitButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 738, 22))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.aboutAction = QtWidgets.QAction(MainWindow)
        self.aboutAction.setObjectName("aboutAction")
        self.menu.addAction(self.aboutAction)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.refreshButton.setText(_translate("MainWindow", "Обновить"))
        self.exportButton.setText(_translate("MainWindow", "Экспорт"))
        self.gotoRow.setPlaceholderText(_translate("MainWindow", "Перейти к номеру..."))
        self.gotoRowOk.setText(_translate("MainWindow", "Ok"))
        self.label.setText(_translate("MainWindow", "Самый дорогой"))
        self.mostExpensivePlayer.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Самый дешевый"))
        self.lessExpensivePlayer.setText(_translate("MainWindow", "TextLabel"))
        self.exitButton.setText(_translate("MainWindow", "Выход"))
        self.menu.setTitle(_translate("MainWindow", "О программе"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.aboutAction.setText(_translate("MainWindow", "About"))
